"""
⚙️ КОНФИГУРАЦИЯ ДЛЯ BOT ANALYZER
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загружаем переменные окружения
load_dotenv()

# ============= ГЛАВНЫЕ НАСТРОЙКИ =============

# Токен Telegram бота
BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")

# ID администратора
ADMIN_IDS = [int(x) for x in os.getenv("ADMIN_IDS", "123456789").split(",")]

# Чат ID для логирования
LOG_CHAT_ID = int(os.getenv("LOG_CHAT_ID", "0"))

# ============= ДИРЕКТОРИИ =============

# Корневая директория проекта
BASE_DIR = Path(__file__).parent

# Директория для временных файлов
TEMP_DIR = BASE_DIR / "temp_bots"
TEMP_DIR.mkdir(exist_ok=True)

# Директория для отчетов
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

# Директория для копий ботов
ANALYZED_BOTS_DIR = BASE_DIR / "analyzed_bots_copies"
ANALYZED_BOTS_DIR.mkdir(exist_ok=True)

# Директория для логов
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

# ============= ЛОГИРОВАНИЕ =============

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_FILE = LOGS_DIR / "bot_analyzer.log"
LOG_FORMAT = "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# ============= ОГРАНИЧЕНИЯ =============

# Максимальный размер анализируемого файла (в байтах)
MAX_FILE_SIZE = int(os.getenv("MAX_FILE_SIZE", "10485760"))  # 10 MB

# Максимальное время анализа (в секундах)
MAX_ANALYSIS_TIME = int(os.getenv("MAX_ANALYSIS_TIME", "300"))  # 5 минут

# Максимум одновременных анализов
MAX_CONCURRENT_ANALYSIS = int(os.getenv("MAX_CONCURRENT_ANALYSIS", "5"))

# Лимит анализов в день для пользователя
DAILY_LIMIT_PER_USER = int(os.getenv("DAILY_LIMIT_PER_USER", "10"))

# ============= АНАЛИЗ =============

# Включить анализ безопасности
ENABLE_SECURITY_ANALYSIS = os.getenv("ENABLE_SECURITY_ANALYSIS", "true").lower() == "true"

# Включить анализ производительности
ENABLE_PERFORMANCE_ANALYSIS = os.getenv("ENABLE_PERFORMANCE_ANALYSIS", "true").lower() == "true"

# Включить анализ стиля кода
ENABLE_STYLE_ANALYSIS = os.getenv("ENABLE_STYLE_ANALYSIS", "true").lower() == "true"

# Включить анализ сложности
ENABLE_COMPLEXITY_ANALYSIS = os.getenv("ENABLE_COMPLEXITY_ANALYSIS", "true").lower() == "true"

# Включить анализ зависимостей
ENABLE_DEPENDENCY_ANALYSIS = os.getenv("ENABLE_DEPENDENCY_ANALYSIS", "true").lower() == "true"

# ============= ГЕНЕРАЦИЯ =============

# Включить генерацию кода
ENABLE_CODE_GENERATION = os.getenv("ENABLE_CODE_GENERATION", "true").lower() == "true"

# Включить генерацию документации
ENABLE_DOCUMENTATION = os.getenv("ENABLE_DOCUMENTATION", "true").lower() == "true"

# Включить генерацию JSON структуры
ENABLE_JSON_EXPORT = os.getenv("ENABLE_JSON_EXPORT", "true").lower() == "true"

# Включить генерацию HTML отчетов
ENABLE_HTML_EXPORT = os.getenv("ENABLE_HTML_EXPORT", "true").lower() == "true"

# ============= TELEGRAM API =============

# URL Telegram Bot API
TELEGRAM_API_URL = "https://api.telegram.org"

# Таймаут для запросов
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "30"))

# ============= ДЕТЕКТИРОВАНИЕ ЯЗЫКОВ =============

SUPPORTED_LANGUAGES = {
    "python": [".py"],
    "javascript": [".js", ".ts"],
    "go": [".go"],
    "rust": [".rs"],
    "java": [".java"],
}

# ============= ДЕТЕКТИРОВАНИЕ ФРЕЙМВОРКОВ =============

BOT_FRAMEWORKS = {
    "aiogram": ["aiogram", "from aiogram"],
    "python-telegram-bot": ["python_telegram_bot", "from telegram"],
    "pyTelegramBotAPI": ["pyTelegramBotAPI", "import telebot"],
    "discord.py": ["discord", "from discord"],
    "interactions": ["interactions", "from interactions"],
}

# ============= ДЕТЕКТИРОВАНИЕ БД =============

DATABASES = {
    "sqlite": ["sqlite3", "aiosqlite"],
    "postgresql": ["psycopg", "asyncpg"],
    "mysql": ["mysql", "pymysql"],
    "mongodb": ["pymongo", "motor"],
    "redis": ["redis", "aioredis"],
}

# ============= ДЕТЕКТИРОВАНИЕ API =============

API_PROVIDERS = {
    "OpenAI": ["openai", "ChatGPT"],
    "Google": ["google", "googleapis"],
    "AWS": ["boto3", "aws"],
    "Stripe": ["stripe", "stripeAPI"],
    "GitHub": ["github", "pygithub"],
    "Twitter": ["tweepy", "twitter"],
}

# ============= TEMPLATES =============

TEMPLATE_BOT_CODE = """
\"\"\"
Bot Template - Generated by Bot Analyzer
\"\"\"

import asyncio
import logging
from aiogram import Bot, Dispatcher, types, F
from aiogram.filters import Command
from aiogram.fsm.context import FSMContext

# Configuration
TOKEN = "PASTE_YOUR_TOKEN_HERE"
logger = logging.getLogger(__name__)

# Initialize bot and dispatcher
bot = Bot(token=TOKEN)
dp = Dispatcher()

# Handlers
@dp.message(Command("start"))
async def cmd_start(message: types.Message):
    await message.answer("Hello! 👋")

# Run bot
async def main():
    await dp.start_polling(bot, skip_updates=True)

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
"""

# ============= СООБЩЕНИЯ =============

MESSAGES = {
    "start": """
👋 Привет, {user_name}!

🤖 Я анализирую боты Telegram и создаю их копии.

📊 Мои возможности:
• Анализ команд и кнопок
• Обнаружение функций
• Проверка безопасности
• Анализ производительности
• Генерация кода
• Создание ZIP копии

❓ Отправь юзернейм бота для анализа
""",
    
    "help": """
🤖 **Как использовать Bot Analyzer**

1️⃣ Отправь юзернейм бота (@username)
2️⃣ Я проанализирую его структуру
3️⃣ Получишь полный отчет и ZIP архив

📋 **Анализируется:**
✓ Команды
✓ Кнопки и меню
✓ Функции
✓ БД и API
✓ Безопасность
✓ Производительность
✓ Стиль кода

📦 **В ZIP архиве:**
• bot_main.py - шаблон кода
• bot_structure.json - структура
• README.md - документация
• config.py - конфиг
• requirements.txt - зависимости
""",
    
    "analyzing": """
🔍 Анализирую бота: @{bot_username}

⏳ Это может занять 30-60 секунд...

Проверяю:
⬜ Команды
⬜ Кнопки
⬜ Функции
⬜ API
⬜ Безопасность
⬜ Производительность
""",
    
    "analysis_complete": """
✅ **Анализ завершен!**

📊 **Результаты:**
• Команд: {commands}
• Кнопок: {buttons}
• Функций: {features}
• БД: {database}
• Сложность: {complexity}

📥 Отправляю ZIP файл...
""",
    
    "error": """
❌ **Ошибка при анализе!**

{error_message}

Пожалуйста, попробуй еще раз или обратись к администратору.
""",
}

# ============= ОГРАНИЧЕНИЯ НА RATE LIMITING =============

RATE_LIMIT_SETTINGS = {
    "messages_per_second": int(os.getenv("RATE_LIMIT_MSG_SEC", "1")),
    "messages_per_minute": int(os.getenv("RATE_LIMIT_MSG_MIN", "30")),
    "messages_per_hour": int(os.getenv("RATE_LIMIT_MSG_HOUR", "500")),
}

# ============= КЕШИРОВАНИЕ =============

# Включить кеширование результатов анализа
ENABLE_CACHE = os.getenv("ENABLE_CACHE", "true").lower() == "true"

# Время кеша (в секундах)
CACHE_TTL = int(os.getenv("CACHE_TTL", "3600"))  # 1 час

# Максимальный размер кеша (в MB)
MAX_CACHE_SIZE = int(os.getenv("MAX_CACHE_SIZE", "100"))

# ============= УВЕДОМЛЕНИЯ =============

# Включить уведомления об ошибках
ENABLE_ERROR_NOTIFICATIONS = os.getenv("ENABLE_ERROR_NOTIFICATIONS", "true").lower() == "true"

# Включить уведомления о начале/конце анализа
ENABLE_PROGRESS_NOTIFICATIONS = os.getenv("ENABLE_PROGRESS_NOTIFICATIONS", "true").lower() == "true"

# ============= СТАТИСТИКА =============

# Включить сбор статистики
ENABLE_STATISTICS = os.getenv("ENABLE_STATISTICS", "true").lower() == "true"

# Сохранять ли статистику в БД
SAVE_STATISTICS_TO_DB = os.getenv("SAVE_STATISTICS_TO_DB", "false").lower() == "true"

# ============= ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ =============

def get_config_dict():
    """Получить все конфиги в виде словаря"""
    return {
        "bot_token": BOT_TOKEN,
        "admin_ids": ADMIN_IDS,
        "log_level": LOG_LEVEL,
        "max_file_size": MAX_FILE_SIZE,
        "max_analysis_time": MAX_ANALYSIS_TIME,
        "daily_limit": DAILY_LIMIT_PER_USER,
        "analysis": {
            "security": ENABLE_SECURITY_ANALYSIS,
            "performance": ENABLE_PERFORMANCE_ANALYSIS,
            "style": ENABLE_STYLE_ANALYSIS,
            "complexity": ENABLE_COMPLEXITY_ANALYSIS,
        },
        "generation": {
            "code": ENABLE_CODE_GENERATION,
            "documentation": ENABLE_DOCUMENTATION,
            "json": ENABLE_JSON_EXPORT,
            "html": ENABLE_HTML_EXPORT,
        },
    }

def validate_config():
    """Проверить конфигурацию на ошибки"""
    errors = []
    
    if not BOT_TOKEN or BOT_TOKEN == "YOUR_BOT_TOKEN_HERE":
        errors.append("BOT_TOKEN не установлен!")
    
    if not ADMIN_IDS:
        errors.append("ADMIN_IDS пустой список!")
    
    if MAX_FILE_SIZE <= 0:
        errors.append("MAX_FILE_SIZE должен быть положительным!")
    
    if MAX_ANALYSIS_TIME <= 0:
        errors.append("MAX_ANALYSIS_TIME должен быть положительным!")
    
    return errors

# Проверяем конфиг при импорте
_errors = validate_config()
if _errors:
    import warnings
    for error in _errors:
        warnings.warn(f"Config warning: {error}", stacklevel=2)

# ============= ТОЧКА ВХОДА =============

if __name__ == "__main__":
    print("⚙️  Конфигурация Bot Analyzer\n")
    print(f"BOT_TOKEN: {BOT_TOKEN[:20]}...")
    print(f"ADMIN_IDS: {ADMIN_IDS}")
    print(f"LOG_LEVEL: {LOG_LEVEL}")
    print(f"BASE_DIR: {BASE_DIR}")
    print(f"\n📁 Директории:")
    print(f"TEMP_DIR: {TEMP_DIR}")
    print(f"REPORTS_DIR: {REPORTS_DIR}")
    print(f"LOGS_DIR: {LOGS_DIR}")
    print(f"\n⚙️  Ограничения:")
    print(f"MAX_FILE_SIZE: {MAX_FILE_SIZE} bytes")
    print(f"MAX_ANALYSIS_TIME: {MAX_ANALYSIS_TIME} sec")
    print(f"DAILY_LIMIT_PER_USER: {DAILY_LIMIT_PER_USER}")
